# Generated by Django 5.0.4 on 2024-04-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_goldrate_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goldrate',
            old_name='thirchur',
            new_name='thrichur',
        ),
    ]
